### ISSUE TITLE
老师，这个python怎么部署到openwrt软路由上面？

### ISSUE THREAD

**Issue by securetron** [MUTED64/GeminiTranslate#1]
电脑不一定开着啊

**Comment by MUTED64** [comment]
1. 要自己部署的话，`main.py` 的最后一行 `port` 参数可以换成你想要的端口号，openwrt终端里设置一个叫 `GOOGLE_API_KEY` 的环境变量，值设置为申请到的密钥，其它的就普通按照 `README` 里部署就行，连接的话直接连接到 `IP:端口号`。
2. 这个项目做出来之后过了一段时间官方插件也支持 Gemini 作为翻译后端了，区别只在于 Prompt 和连接策略略有区别，你也可以考虑更新到最新版本的沉浸式翻译直接使用，不用在 openwrt 上部署。
